const SIGN_IN_TO_SITE = 'SIGN_IN_TO_SITE';
const SET_ERROR_STATE = 'SET_ERROR_STATE';
const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
const SET_SEARCH_PRODUCT_RESULT = 'SET_SEARCH_PRODUCT_RESULT';
const CLEAR_SEARCH_RESULT = 'CLEAR_SEARCH_RESULT';
const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS';
const SET_PRODUCT_DETAILS = 'SET_PRODUCT_DETAILS';
const CLEAR_PRODUCT_DETAILS = 'CLEAR_PRODUCT_DETAILS';

export {
    SIGN_IN_TO_SITE, 
    SET_ERROR_STATE,
    SEARCH_PRODUCT,
    SET_SEARCH_PRODUCT_RESULT,
    CLEAR_SEARCH_RESULT,
    GET_PRODUCT_DETAILS,
    SET_PRODUCT_DETAILS,
    CLEAR_PRODUCT_DETAILS
};